# Eclipse Mosquitto v2.0 — spicy-merkaat
# Sin autenticación por ahora (dev). Para producción: añadir password_file y TLS.

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

connection_messages true
